/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpIndexRouteImport } from './routes/sign-up/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as TweetsTweetIdRouteImport } from './routes/tweets/$tweetId'
import { Route as ProfileProfileIDRouteImport } from './routes/profile/$profileID'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const TweetsTweetIdRoute = TweetsTweetIdRouteImport.update({
  id: '/tweets/$tweetId',
  path: '/tweets/$tweetId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileProfileIDRoute = ProfileProfileIDRouteImport.update({
  id: '/profile/$profileID',
  path: '/profile/$profileID',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile/$profileID': typeof ProfileProfileIDRoute
  '/tweets/$tweetId': typeof TweetsTweetIdRoute
  '/explore': typeof ExploreIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/sign-up': typeof SignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile/$profileID': typeof ProfileProfileIDRoute
  '/tweets/$tweetId': typeof TweetsTweetIdRoute
  '/explore': typeof ExploreIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/sign-up': typeof SignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile/$profileID': typeof ProfileProfileIDRoute
  '/tweets/$tweetId': typeof TweetsTweetIdRoute
  '/explore/': typeof ExploreIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile/$profileID'
    | '/tweets/$tweetId'
    | '/explore'
    | '/profile'
    | '/sign-in'
    | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile/$profileID'
    | '/tweets/$tweetId'
    | '/explore'
    | '/profile'
    | '/sign-in'
    | '/sign-up'
  id:
    | '__root__'
    | '/'
    | '/profile/$profileID'
    | '/tweets/$tweetId'
    | '/explore/'
    | '/profile/'
    | '/sign-in/'
    | '/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileProfileIDRoute: typeof ProfileProfileIDRoute
  TweetsTweetIdRoute: typeof TweetsTweetIdRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  SignInIndexRoute: typeof SignInIndexRoute
  SignUpIndexRoute: typeof SignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tweets/$tweetId': {
      id: '/tweets/$tweetId'
      path: '/tweets/$tweetId'
      fullPath: '/tweets/$tweetId'
      preLoaderRoute: typeof TweetsTweetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$profileID': {
      id: '/profile/$profileID'
      path: '/profile/$profileID'
      fullPath: '/profile/$profileID'
      preLoaderRoute: typeof ProfileProfileIDRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileProfileIDRoute: ProfileProfileIDRoute,
  TweetsTweetIdRoute: TweetsTweetIdRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SignInIndexRoute: SignInIndexRoute,
  SignUpIndexRoute: SignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
